# Secret resources for storing sensitive configuration
# Note: In production, you should use a solution like Sealed Secrets,
# External Secrets Operator, or Azure Key Vault integration instead
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  labels:
    app: {{ .Values.backend.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    environment: {{ .Values.global.environment }}
type: Opaque
data:
  # This is a placeholder. In real deployments, provide this via CI/CD or external secrets management
  db-connection-string: {{ "YOUR_CONNECTION_STRING_HERE" | b64enc }}
