# Kubernetes Deployment for the frontend application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  labels:
    app: {{ .Values.frontend.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    environment: {{ .Values.global.environment }}
spec:
  {{- if not .Values.frontend.autoscaling.enabled }}
  replicas: {{ .Values.frontend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
        environment: {{ .Values.global.environment }}
    spec:
      containers:
        - name: {{ .Values.frontend.name }}
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
          env:
            - name: REACT_APP_ENVIRONMENT
              value: {{ .Values.frontend.env.REACT_APP_ENVIRONMENT }}
            - name: REACT_APP_API_URL
              value: "https://{{ (index .Values.backend.ingress.hosts 0).host }}/api"
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
